"""description

Revision ID: 518c91f273a8
Revises: 9db0f36b0ae9
Create Date: 2026-05-04 23:14:35.607644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518c91f273a8'
down_revision = '9db0f36b0ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
